version: '3'
services:
  cms:
    image: ryannhg/oni-cms:cors
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: password
    links:
      - db:mysql
  db:
    image: ryannhg/oni-db:cors
    ports:
      - 3306:3306
    volumes:
      - ./cms/wordpress-content.sql:/docker-entrypoint-initdb.d/wordpress-content.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build:
      context: ./web
    ports:
      - 3000:3000
    volumes:
      - ./web/src:/usr/src/app/src
    links:
      - cms:cms
  # TODO: backup (creates content and configuration sql dumps based)