version: '3'
services:
  cms:
    image: ryannhg/oni-cms:blog-demo
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: password
    links:
      - db:mysql
  db:
    image: ryannhg/oni-db:blog-demo
    volumes:
      - ./cms/wordpress-content.sql:/docker-entrypoint-initdb.d/wordpress-content.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
  # TODO: backup (creates content and configuration sql dumps based)
  # TODO: web (nodejs web server using wpapi)
