version: '3'
services:

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./cms/backups:/docker-entrypoint-initdb.d

  cms:
    build:
      context: ./cms
      dockerfile: Dockerfile
    image: ryannhg/oni-cms
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: password
      WP_ENDPOINT_URL: http://publisher/api
      WP_SECRET_TOKEN: super-secret-token
      WP_ADMIN_USER: admin
      WP_ADMIN_EMAIL: admin@onenorth.com
      WP_ADMIN_PASSWORD: password
    volumes:
      - ./cms/plugins/publish-hook:/var/www/html/wp-content/plugins/publish-hook
      - ./cms/plugins/keep-live-posts:/var/www/html/wp-content/plugins/keep-live-posts
      - ./cms/plugins/publish-buttons:/var/www/html/wp-content/plugins/publish-buttons
    links:
      - mysql

  publisher:
    build:
      context: ./publisher
      dockerfile: Dockerfile
    image: ryannhg/oni-publisher
    environment:
      WP_SECRET_TOKEN: super-secret-token
      LIVE_MONGO_URI: mongodb://mongo/cms-live
      PREVIEW_MONGO_URI: mongodb://mongo/cms-preview
    volumes:
      - ./publisher/app.js:/usr/src/app/app.js
      - ./publisher/data.js:/usr/src/app/data.js
      - ./publisher/logic.js:/usr/src/app/logic.js
    links:
      - cms

  mongo:
    image: mongo

  web-live:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ryannhg/oni-web
    environment:
      MONGO_URI: mongodb://mongo/cms-live
    ports:
      - 3000:80
    volumes:
      - ./web/app.js:/usr/src/app/app.js
    links:
      - mongo

  web-preview:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ryannhg/oni-web:latest
    environment:
      MONGO_URI: mongodb://mongo/cms-preview
    ports:
      - 4000:80
    volumes:
      - ./web/app.js:/usr/src/app/app.js
    links:
      - mongo
