version: '3'
services:

  mysql:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  cms:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: password
      WP_ENDPOINT_URL: http://worker/api
      WP_SECRET_TOKEN: super-secret-token
    volumes:
      - ${PWD}/cms/publish-hook:/var/www/html/wp-content/plugins/publish-hook
    links:
      - mysql

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - 5000:80
      - 5001:9229
    environment:
      WP_SECRET_TOKEN: super-secret-token
      LIVE_MONGO_URI: mongodb://mongo/cms-live
      PREVIEW_MONGO_URI: mongodb://mongo/cms-preview
    volumes:
      - ./worker:/usr/src/app
    links:
      - cms

  mongo:
    image: mongo
    ports:
      - 27017:27017

  web-live:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      MONGO_URI: mongodb://mongo/cms-live
    ports:
      - 3000:80
      - 3001:9229
    volumes:
      - ./web:/usr/src/app
    links:
      - mongo

  web-preview:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      MONGO_URI: mongodb://mongo/cms-preview
    ports:
      - 4000:80
      - 4001:9229
    volumes:
      - ./web:/usr/src/app
    links:
      - mongo
