version: '3'
services:
  cms:
    image: ryannhg/oni-cms
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: password
    links:
      - db:mysql
  db:
    image: ryannhg/oni-db
    environment:
      MYSQL_ROOT_PASSWORD: password
