version: '3'
services:

  mysql:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  cms:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: password
      WP_ENDPOINT_URL: http://worker/api
      WP_SECRET_TOKEN: super-secret-token
    volumes:
      - ${PWD}/cms/publish-hook:/var/www/html/wp-content/plugins/publish-hook
    links:
      - mysql

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      WP_SECRET_TOKEN: super-secret-token
    volumes:
      - ./worker:/usr/src/app
    links:
      - cms

  mongo:
    image: mongo
    ports:
      - 27017:27017

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./web:/usr/src/app
    links:
      - mongo
