version: '3'
services:
  cms:
    image: ryannhg/oni-cms
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: password
    links:
      - db:mysql
    expose:
      - 80
  db:
    image: ryannhg/oni-db
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build:
      context: ./web
    image: ryannhg/oni-web
    environment:
      WP_HOST: cms
      WP_PORT: 80
    volumes:
      - ./web/app.js:/usr/src/app/app.js
    links:
      - cms
    ports:
      - 3000:3000
